### ISSUE TITLE
read_parquet engine parameter: 'fastparquet' vs. default 'auto' argument

### ISSUE THREAD

**Issue by sansbacon** [cooperdff/nfl_data_py#11]
Pandas will try pyarrow and default back to fastparquet if pyarrow is unavailable. Is there a specific reason you are specifying engine='fastparquet' because, if not, I think it would be better to leave it as the default 'auto' argument.

**Comment by cooperdff** [comment]
No, when I wrote the script originally I was having trouble with pyarrow so changed to fastparquet but I'm perfectly fine changing it to auto.

**Comment by cooperdff** [comment]
I'm planning on pushing another update this weekend including an added step to the clean_data() function and a new more comprehensive file for import_schedule() function, I'll include this change in that update.

**Comment by sansbacon** [comment]
Sounds good. I'll go ahead and close this.
