### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by sansbacon** [cooperdff/nfl_data_py#12]
I think the library would benefit from having a caching strategy for downloaded or processed files. One option is to download the files outside of pandas and use an http cache. This tends to be temporary, no more than 7 days. Another option is to give the user the option to read from and save to a cache, which could just involve reading/writing parquet files from the existing data directory, which would be more permanent, or to the system tmp directory, which is more transient. Let me know if either option is of interest.

**Comment by cooperdff** [comment]
That sounds like a great idea, the second option that would be more permanent sounds like the preferable option to me but let me know if you think we'd be better off going a different direction.

**Comment by sansbacon** [comment]
OK, I'll put together a plan and get back to you.

**Comment by scottiegarcia** [comment]
I'd recommend using the user's system's cache directory for doing so. [appdirs](https://github.com/ActiveState/appdirs) is a simple module for determining that location. Happy to help if you'd like.

**Comment by sansbacon** [comment]
Thanks for pointing us to appdirs - I hadn't seen library that before and it is very handy. In terms of storage strategy, I was looking at a partitioned parquet file by year for the play-by-play. My instinct is that the weekly / seasonal player and team stats and the other datafiles are not large enough to worry about partitioning.

**Comment by scottiegarcia** [comment]
Yeah that's the only one worth the effort

**Comment by cooperdff** [comment]
Had a chance to take a run at this this morning - newest release includes a cache_pbp() function for local caching. I'm going to go ahead and close this issue and if anyone has recommendations for further improvements to that function we can open up another one.
