### ISSUE TITLE
import_pbp_data function not working

### ISSUE THREAD

**Issue by Josephhero** [cooperdff/nfl_data_py#19]
when trying to run the function import_pbp_data, I receive the following error message: No such file or directory: [path]

Code: 
`import nfl_data_py as nfl 
data = nfl.import_pbp_data([2021])`

<img width="806" alt="Screen Shot 2021-09-21 at 5 41 50 PM" src="https://user-images.githubusercontent.com/21974312/134265774-e1495be5-fe31-4b76-9a35-496dffdc56a4.png">

**Comment by cooperdff** [comment]
Resolved in latest release.
