### ISSUE TITLE
ID Tables Small Issue?

### ISSUE THREAD

**Issue by robertryanharrison** [cooperdff/nfl_data_py#27]
Hi, i'm a newb and this is my first issue post so please delete if this is wrong.  I suspect your code is fine and that the source data has some bugs, but i'm not sure who to alert to help them out.  

I believe there are some slight data issues on the player ID table. 

probably some more than listed below, but i have to run for now.  these are pretty small things, doubtful they will be relevant to anything imminent for anyone...  i ran into it on a merge i was doing on gsis_id that didn't like my many-to-one relationship because of it.  i'm happy to share and/or try to help fix if manual edits are an option (i stink at coding though)

1)
**gsis_id** has four duplications:  00-0020270, 00-0019641, 00-0016098, and 00-0029435.
On further research, each of these same cases also has a duplication of the **pff_id**.
There are no other pff_id duplications.

2)
espn_ids have some duplication:  17257, 2578554, 2574009, 5774, 5730, 12771, 2516049, 13490, 2574010, 14660, 2582138, 16094, 17101.  i'm not sure the source of all of these - some seem to be extremely similar names but different people and others seem to be typos (e.g. 5774 one of them should simply be 15774).

3)
**yahoo_ids** have one dup:  33495.  the one from Duke should be 33542

**Comment by alecglen** [comment]
Welcome to the club, @robertryanharrison!

You're correct that it's an issue in the source data. In this case that is sourced from a CSV [over here](https://github.com/dynastyprocess/data/blob/master/files/db_playerids.csv) - could you please make an issue in that project?

**Comment by robertryanharrison** [comment]
Yes!  Will do, thanks for pointing me in the right direction!
