### ISSUE TITLE
Roster Data stop working

### ISSUE THREAD

**Issue by Soteloemma12** [cooperdff/nfl_data_py#28]
Hi, the data of the 2022 roster is not available anymore.
Thanks

**Comment by alecglen** [comment]
Hi @Soteloemma12! Could you please some details to this? What command are you running and what error are you receiving?

**Comment by alecglen** [comment]
Closing as stale and unable to reproduce. @Soteloemma12 please open a new issue with the details I mentioned above if you are still having problems.
