### ISSUE TITLE
Pandas version incompatibility

### ISSUE THREAD

**Issue by alecglen** [cooperdff/nfl_data_py#30]
Per [discussion in nflverse discord](https://discord.com/channels/789805604076126219/789817315368894495/1009670987253547078).

Release 0.2.7 updated Pandas to a version not compatible with Python 3.6. This requirement should be reverted if possible. Alternatively if functionality in the updated Pandas is found to be needed, then the package metadata should be updated to specify it requires Python >= 3.7.

**Comment by cooperdff** [comment]
Resolved in release 0.2.11, requirements updated to Python >= 3.6 and pandas requirements reduced to > 1.
