### ISSUE TITLE
Documentation incorrect on pypi

### ISSUE THREAD

**Issue by dgeitheim** [cooperdff/nfl_data_py#34]
Hi, thanks for making/maintaining this repo. On [the documentation pypi page](https://pypi.org/project/nfl-data-py/) I noticed a minor mistake for `nfl.import_ngs_data(stat_type, years)`: it says `columns : required, type of data (passing, rushing, receiving)` but it should probably say `stat_type (str): type of stats to pull (receiving, passing, rushing)` or something along those lines.

**Comment by alecglen** [comment]
Thanks for pointing this out, @dgeitheim! Fixed it in #51
