### ISSUE TITLE
HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by andre03051** [cooperdff/nfl_data_py#36]
There's a chance the links have changed in nflfastR.  This link doesn't seem to work:
data = pandas.read_parquet(r'https://github.com/nflverse/nflfastR-data/raw/master/data/player_stats.parquet', engine='auto')

Using Python v3.10.7 with nfl_data_py v0.2.5
**Call:**
nfl.import_weekly_data([2021, 2022])
**Error:**
HTTPError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_15024/1768614258.py in <module>
----> 1 nfl.import_weekly_data([2021, 2022])

c:\Users\andre\AppData\Local\Programs\Python\Python310\lib\site-packages\nfl_data_py\__init__.py in import_weekly_data(years, columns, downcast)
    215 
    216     # read weekly data
--> 217     data = pandas.read_parquet(r'https://github.com/nflverse/nflfastR-data/raw/master/data/player_stats.parquet', engine='auto')
    218     data = data[data['season'].isin(years)]
    219 

c:\Users\andre\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parquet.py in read_parquet(path, engine, columns, storage_options, use_nullable_dtypes, **kwargs)
    493     impl = get_engine(engine)
    494 
--> 495     return impl.read(
    496         path,
    497         columns=columns,

c:\Users\andre\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parquet.py in read(self, path, columns, use_nullable_dtypes, storage_options, **kwargs)
    230             to_pandas_kwargs["split_blocks"] = True  # type: ignore[assignment]
    231 
--> 232         path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
    233             path,
    234             kwargs.pop("filesystem", None),
...
--> 643         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    644 
    645 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 404: Not Found

**Comment by cooperdff** [comment]
Hi @andre03051 - you’re right, that data was relocated by the nflfastR team over the offseason. To access it now you should upgrade to v0.3.0.
