### ISSUE TITLE
Data Dictionary

### ISSUE THREAD

**Issue by DavidAllyn68** [cooperdff/nfl_data_py#38]
Hey guys - thanks for pulling this all together!!!  Do you have a data dictionary explaining the columns?  Most are self explanatory, but a few are cryptic (e.g. in weekly_data dakota, pacr, racr, wopr, and ..._epa).

**Comment by alecglen** [comment]
Hi @DavidAllyn68! This project is mostly a wrapper of data compiled by the [nflfastR community](https://discord.com/invite/5Er2FBnnQa), and as such, [their documentation](https://www.nflfastr.com/index.html) holds what you're looking for. It can take a little searching to find the correct mapping from their function names to these - [here](https://www.nflfastr.com/reference/calculate_player_stats.html) is the page for weekly_data!

**Comment by DavidAllyn68** [comment]
Thanks!

Best Regards,
*David Allyn*
***@***.***
LinkedIn <https://www.linkedin.com/pub/david-allyn/4/1aa/252>
Twitter: @DavidAllyn68 <https://twitter.com/DavidAllyn68>

**Comment by Alex-Bishka** [comment]
Was looking through this, and the [vignettes](https://cran.r-project.org/web/packages/nflreadr/vignettes/), but I'm still confused by a couple of stats.

For example, `wopr_x` and `wopr_y` are in the seasonal data, but I only see a definition for for `wopr`:
```
Weighted OPportunity Rating - 1.5 x target_share + 0.7 x air_yards_share - a weighted average that contextualizes total fantasy usage.
```

What do the letters `x` and `y` mean? Expected and actual? Horizontal and vertical? Is there a more detailed resource available somewhere?

Thanks!
