### ISSUE TITLE
Data Dictionary for import_seasonal_data()

### ISSUE THREAD

**Issue by skolActuary** [cooperdff/nfl_data_py#47]
I'm new to Github so forgive me. Ultimately, I want to find routes for WR run by year. I was hoping I could get back into that with a field like RACR but I don't know what a lot of them mean. Could you help define those values? Thanks.

**Comment by alecglen** [comment]
Hello there, fellow Vikings fan! This package is really a Python wrapper for data maintained by a team over at [nflverse](https://github.com/nflverse), so you can reference their documentation for field definitions. Navigating the mapping from their feeds to our functions can definitely get confusing though; feel free to reach out here or in the nflverse Discord with any questions.

I believe the definitions for all `import_seasonal_data()` fields can be found here: https://www.nflfastr.com/reference/calculate_player_stats.html

**Comment by skolActuary** [comment]
Thank you good sir! This specific Github has helped me tremendously.
