### ISSUE TITLE
weekly player data

### ISSUE THREAD

**Issue by bhibby** [cooperdff/nfl_data_py#48]
sorry if this is a dumb question but is this information available in nfl_data_py?

[load_player_stats()]
Load Player Level Weekly Stats

reference: (https://www.nflfastr.com/reference/load_player_stats.html)

**Comment by bhibby** [comment]
nvm I think I found it

**Comment by alecglen** [comment]
Glad you found it, @bhibby! For future reference, the equivalent method is called `import_weekly_data()`.
