### ISSUE TITLE
[question] NFL Data Update Schedule

### ISSUE THREAD

**Issue by Snixells** [cooperdff/nfl_data_py#56]
Hello! I'd like to use the NFL data for weekly game statistics. When is this data updated? For instance, when can I access the play-by-play for Week 1 of the 2023 season? I couldn't find this info elsewhere. Thank you very much in advance!

**Comment by alecglen** [comment]
Hey @Snixells! The pbp dataset for the current season updates nightly around 2AM ET.

Closing this since there's no dev work needed, but feel free to ask any follow-up questions 😄
