### ISSUE TITLE
import_weekly_rosters

### ISSUE THREAD

**Issue by TravisTilteau** [cooperdff/nfl_data_py#62]
Hello,

I noticed that in the github for this project there is a import weekly rosters option, but in the pypi page there isn't one, and it doesn't appear to exist when I install the package. I was curious if this was a coming feature or just a typo?

Thanks

**Comment by alecglen** [comment]
Hey @TravisTilteau - You are correct, it is an upcoming feature. We should have that released in the package in the next few days, but if you need it sooner, you can install with pre-release version with the following command:
`python -m pip install git+ssh://git@github.com/cooperdff/nfl_data_py.git`
