### ISSUE TITLE
get_team_game_log doesn't return game results for current season

### ISSUE THREAD

**Issue by klassy1016** [cooperdff/nfl_data_py#67]
Took a look at the code and it looks like the issue is that when you're iterating over each game in the season. You're casting the points / yardages values to ints. However, the value that is scraped is an empty string when the game hasn't yet occurred causing the cast to fail.

I'd suggest either wrapping the entire parsing block in a try/except or adding empty string handling to each int cast. Happy to make a PR with each option if you'd like me to.

**Comment by alecglen** [comment]
Hey @klassy1016! Sorry, which function are you referring to?

**Comment by klassy1016** [comment]
Oh wow, my apologies. I posted to the wrong repo. My apologies!
