### ISSUE TITLE
import_weekly_data returns shortened list

### ISSUE THREAD

**Issue by lukastheblack** [cooperdff/nfl_data_py#72]
I am trying to get a list of player ids with name and position. When I use the following 

player = nfl.import_weekly_data([2023], ['player_id', 'player_name','position'],downcast=False) 
print(player)

It outputs

       player_id   player_name position
0     00-0023459     A.Rodgers       QB
1     00-0024243       M.Lewis       TE
2     00-0026498    M.Stafford       QB
3     00-0026498    M.Stafford       QB
4     00-0026498    M.Stafford       QB
...          ...           ...      ...
1235  00-0039164  A.Richardson       QB
1236  00-0039164  A.Richardson       QB
1237  00-0039165  Z.Charbonnet       RB
1238  00-0039165  Z.Charbonnet       RB
1239  00-0039165  Z.Charbonnet       RB

I would like to output all 1239( Rather ALL) Player IDs with stats to a file. I didn't see any other issues reported so I Know I'm doing something wrong, can anyone point me in the right direction?

**Comment by alecglen** [comment]
Hey @lukastheblack! Guessing you got this figured out?

Just in case:
The print-out truncates it for readability, but the full dataset is still there in the `player` object (a Pandas dataframe). You can write it to a file using your choice of Pandas methods, for example `player.to_csv("players.csv")`.
